### ISSUE TITLE
BBPress issue with plugin

### ISSUE THREAD

**Issue by saltywd** [BhargavBhandari90/comment-mention#8]
I have a BBPress forum with WordPress installed and Avada Theme.  I am not able to use the @mention function anywhere on my forums within BBPress.  I do not have buddypress installed. Strictly BBPress as my forums. Installed Plugins for the Forum are:
Ultimate Member and a few of there extensions
BBP Style Pack
Comment Mention
BBPress
BBP Notify
GD BBPress Attachments

Thanks for any info and help.

**Comment by saltywd** [comment]
OKAY, looks like it is working on BBPress for the Text editor but NOT on the visual editor.  Anyway to make it work on both?

**Comment by BhargavBhandari90** [comment]
Thanks for the info. I'll try to fix that.

**Comment by saltywd** [comment]
> Thanks for the info. I'll try to fix that.

Thanks very much

**Comment by saltywd** [comment]
A second question is there a way to @all to allow all users to be alerted to a topic or reply?

**Comment by BhargavBhandari90** [comment]
Currently No.

Great idea. This could be in my next update for the Pro plugin :)

**Comment by saltywd** [comment]
> Currently No.
> 
> Great idea. This could be in my next update for the Pro plugin :)

Awesome!! I would still like to be able to be able to use @mentions with the visual editor and not just the plain text editor.

**Comment by BhargavBhandari90** [comment]
> Awesome!! I would still like to be able to be able to use @mentions with the visual editor and not just the plain text editor.

Yes will try to fix this in next update

**Comment by saltywd** [comment]
> > Awesome!! I would still like to be able to be able to use @mentions with the visual editor and not just the plain text editor.
> 
> Yes will try to fix this in next update

Thanks look forward to it!! @BhargavBhandari90 I will upgrade to Pro as well.

**Comment by BhargavBhandari90** [comment]
This is fixed. Please update the plugin to latest version

**Comment by saltywd** [comment]
It works perfectly in visual editor. Anyway to do the @all to notify all members?

**Comment by BhargavBhandari90** [comment]
Sorry, it's not there.
